### ISSUE TITLE
Next 13 App router Issue

### ISSUE THREAD

**Issue by femi-Zedev** [BuilderIO/hydration-overlay#25] opened 2023-12-27 13:56 UTC
I'm using Next 13 App router and I've configured my next.config like in the demo
```typescript
const {
  withHydrationOverlay,
} = require("@builder.io/react-hydration-overlay/next")

/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = withHydrationOverlay({
  /**
   * Optional: `appRootSelector` is the selector for the root element of your app. By default, it is `#__next` which works
   * for Next.js apps with pages directory. If you are using the app directory, you should change this to `main`.
   */
  appRootSelector: "main",
})(nextConfig);
```
And I went to my RootLayout and wrapped the whole app as recommanded like
```typescript
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
       <HydrationOverlay>
          {children}
       </HydrationOverlay>
      </body>
    </html>
  )
}
``` 
But hydration errors still display the same

**Comment by femi-Zedev** [comment] 2023-12-27 13:59
> I'm using Next 13 App router and I've configured my next.config like in the demo
> 
> ```ts
> const {
>   withHydrationOverlay,
> } = require("@builder.io/react-hydration-overlay/next")
> 
> /** @type {import('next').NextConfig} */
> const nextConfig = {};
> 
> module.exports = withHydrationOverlay({
>   /**
>    * Optional: `appRootSelector` is the selector for the root element of your app. By default, it is `#__next` which works
>    * for Next.js apps with pages directory. If you are using the app directory, you should change this to `main`.
>    */
>   appRootSelector: "main",
> })(nextConfig);
> ```
> 
> And I went to my RootLayout and wrapped the whole app as recommanded like
> 
> ```ts
> export default function RootLayout({
>   children,
> }: {
>   children: React.ReactNode
> }) {
>   return (
>     <html lang="en">
>       <body>
>        <HydrationOverlay>
>           {children}
>        </HydrationOverlay>
>       </body>
>     </html>
>   )
> }
> ```
> 
> But hydration errors still display the same

I'm wrapped the html tag also and it worked

**Comment by samijaber** [comment] 2024-01-02 17:02
Could you provide a minimum reproduction? Does it work with Next14 for you? 

This test is running Next14 + App dir and works as expected: https://github.com/BuilderIO/hydration-overlay/tree/main/tests/next-app-dir

**Comment by iusedebian** [comment] 2024-01-04 16:00
same here, tried 14.0.3 and 14.0.4

**Comment by iusedebian** [comment] 2024-01-04 16:01
> Could you provide a minimum reproduction? Does it work with Next14 for you?
> 
> This test is running Next14 + App dir and works as expected: https://github.com/BuilderIO/hydration-overlay/tree/main/tests/next-app-dir

I have the same issue
repo is public: https://github.com/iusedebian/workout-tracker

**Comment by samijaber** [comment] 2024-01-04 16:51
@iusedebian Your repo is far too complex. A minimum reproduction is a codebase that is as small as possible, with only the bare minimum code that still showcases the bug (See StackOverflow's [definition](https://stackoverflow.com/help/minimal-reproducible-example)). I can't debug the issue using this codebase.

**Comment by iusedebian** [comment] 2024-01-04 17:17
> @iusedebian Your repo is far too complex. A minimum reproduction is a codebase that is as small as possible, with only the bare minimum code that still showcases the bug (See StackOverflow's [definition](https://stackoverflow.com/help/minimal-reproducible-example)). I can't debug the issue using this codebase.

ok i made a new one https://github.com/iusedebian/hydration-overlay

but I think it's because it doesnt catch wrong html nestings or the nextjs localhost bug

**Comment by samijaber** [comment] 2024-01-04 17:50
Thanks a lot! I see what the issue is: I am recommending `appRootSelector: 'main'` as that is how NextJS App projects are scaffolded. You are removing `<main>` as the wrapper of your application, hence why you do not see the diff.

I see the same thing happening in your main project as well. @femi-Zedev I am closing this issue assuming it is also a similar mistake with `appRootSelector`.

**Closed by samijaber** 2024-01-04 17:50 UTC
